DECLARE
    V_ID                        NUMBER;
    V_RUN                       VARCHAR2(100);
    V_DV                        VARCHAR2(10);
    V_PNOMBRE                   VARCHAR2(100);
    V_SNOMBRE                   VARCHAR2(100);
    V_APPATERNO                 VARCHAR2(100);
    V_APMATERNO                 VARCHAR2(100);
    V_ESTADO_CIVIL              VARCHAR2(100);
    V_SUELDO                    NUMBER;
    V_CONTRATO                  DATE;
    V_NAC                       DATE;
    
            
    V_MIN                       NUMBER;
    V_MAX                       NUMBER;
    V_ANNOS_TRABAJANDO          NUMBER;
    NOMBRE_USUARIO              VARCHAR2(100):='';
    CLAVE_USUARIO               VARCHAR2(100):='';
    NOMBRE_COMPLETO             VARCHAR2(100):='';
BEGIN
    SELECT MIN(ID_EMP), MAX(ID_EMP)
    INTO V_MIN, V_MAX
    FROM EMPLEADO;

    WHILE V_MIN <= V_MAX LOOP
        SELECT E.ID_EMP,
        E.NUMRUN_EMP,
        E.DVRUN_EMP,
        E.PNOMBRE_EMP,
        E.SNOMBRE_EMP,
        E.APPATERNO_EMP,
        E.APMATERNO_EMP,
        EC.NOMBRE_ESTADO_CIVIL,
        E.SUELDO_BASE,
        E.FECHA_CONTRATO,
        E.FECHA_NAC
        INTO V_ID, V_RUN, V_DV, V_PNOMBRE, V_SNOMBRE, V_APPATERNO, V_APMATERNO, V_ESTADO_CIVIL, V_SUELDO, 
        V_CONTRATO, V_NAC
        FROM EMPLEADO E
        JOIN ESTADO_CIVIL EC ON (E.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL)
        WHERE E.ID_EMP = V_MIN;
    
    
        NOMBRE_USUARIO:= LOWER(SUBSTR(V_ESTADO_CIVIL, 1,1));
        NOMBRE_USUARIO:= NOMBRE_USUARIO||SUBSTR(V_PNOMBRE,1,3);
        NOMBRE_USUARIO:= NOMBRE_USUARIO||LENGTH(V_PNOMBRE);
        NOMBRE_USUARIO:= NOMBRE_USUARIO||'*';
        NOMBRE_USUARIO:= NOMBRE_USUARIO||SUBSTR(V_SUELDO, -1, 1);
        NOMBRE_USUARIO:= NOMBRE_USUARIO||V_DV;
        V_ANNOS_TRABAJANDO := TRUNC(MONTHS_BETWEEN(SYSDATE, V_CONTRATO) / 12);
        IF V_ANNOS_TRABAJANDO < 10          THEN
            NOMBRE_USUARIO:= NOMBRE_USUARIO||V_ANNOS_TRABAJANDO||'X';
        ELSE    
            NOMBRE_USUARIO:= NOMBRE_USUARIO||V_ANNOS_TRABAJANDO;
        END IF;
        
        CLAVE_USUARIO:= SUBSTR(V_RUN,3,1);
        CLAVE_USUARIO:=CLAVE_USUARIO||EXTRACT(YEAR FROM V_NAC)+2;
        CLAVE_USUARIO:=CLAVE_USUARIO||SUBSTR(V_SUELDO,-1,3)-1;
        IF V_ESTADO_CIVIL = 'CASADO' OR V_ESTADO_CIVIL = 'ACUERDO DE UNION CIVIL'   THEN
            CLAVE_USUARIO:=CLAVE_USUARIO||SUBSTR(V_APPATERNO,1,2);
        ELSIF V_ESTADO_CIVIL = 'DIVORCIADO' OR V_ESTADO_CIVIL = 'SOLTERO'           THEN
            CLAVE_USUARIO:=CLAVE_USUARIO||SUBSTR(V_APPATERNO,1,1);
            CLAVE_USUARIO:=CLAVE_USUARIO||SUBSTR(V_APPATERNO,-1,1);
        ELSIF V_ESTADO_CIVIL = 'VIUDO'                                              THEN
            CLAVE_USUARIO:=CLAVE_USUARIO||SUBSTR(V_APPATERNO,-2,2);
        ELSIF V_ESTADO_CIVIL = 'SEPARADO'                                           THEN
            CLAVE_USUARIO:=CLAVE_USUARIO||SUBSTR(V_APPATERNO,-1,2);
        END IF;
        CLAVE_USUARIO:=CLAVE_USUARIO||V_ID;
        CLAVE_USUARIO:=CLAVE_USUARIO||EXTRACT(MONTH FROM SYSDATE)||EXTRACT(YEAR FROM SYSDATE);
        NOMBRE_COMPLETO:=V_PNOMBRE||' '||V_SNOMBRE||' '||V_APPATERNO||' '||V_APMATERNO;
            
        INSERT INTO USUARIO_CLAVE VALUES(V_MIN, V_RUN, V_DV, NOMBRE_COMPLETO, NOMBRE_USUARIO, CLAVE_USUARIO);
        V_MIN:=V_MIN+10;
    END LOOP;
END;
TRUNCATE TABLE USUARIO_CLAVE;
SELECT * FROM USUARIO_CLAVE;