--CASO 1--
VARIABLE B_ANNO_PROCESO     NUMBER;
EXEC :B_ANNO_PROCESO:=EXTRACT(YEAR FROM SYSDATE);

VARIABLE B_COMUNA1          VARCHAR2;
EXEC :B_COMUNA1:='Mar�a Pinto';

VARIABLE B_COMUNA2          VARCHAR2;
EXEC :B_COMUNA2:='Curacav�';

VARIABLE B_COMUNA3          VARCHAR2;
EXEC :B_COMUNA3:='Talagante';

VARIABLE B_COMUNA4          VARCHAR2;
EXEC :B_COMUNA4:='El Monte';

VARIABLE B_COMUNA5          VARCHAR2;
EXEC :B_COMUNA5:='Buin';

DECLARE
    V_ID            NUMBER;
    V_RUN           VARCHAR2(100);
    V_DV            VARCHAR2(100);
    V_NOMBRE        VARCHAR2(100);
    V_COMUNA        VARCHAR2(100);
    V_SUELDO        NUMBER;
    V_MIN           NUMBER;
    V_MAX           NUMBER;
    PORC_MOVIL_NORMAL        NUMBER;
    VALOR_MOVIL_NORMAL       NUMBER;
    VALOR_MOVIL_EXTRA        NUMBER;
    VALOR_TOTAL_MOVIL        NUMBER;
BEGIN
    SELECT MIN(ID_EMP), MAX(ID_EMP)
    INTO V_MIN, V_MAX
    FROM EMPLEADO;
    
    LOOP
        SELECT E.ID_EMP,
        E.NUMRUN_EMP, 
        E.DVRUN_EMP,
        E.PNOMBRE_EMP||' '||E.SNOMBRE_EMP||' '||E.APPATERNO_EMP||' '||E.APMATERNO_EMP,
        C.NOMBRE_COMUNA,
        E.SUELDO_BASE
        INTO V_ID, V_RUN, V_DV, V_NOMBRE, V_COMUNA, V_SUELDO
        FROM EMPLEADO E
        JOIN COMUNA C ON (E.ID_COMUNA = C.ID_COMUNA)
        WHERE E.ID_EMP = V_MIN;
    
        PORC_MOVIL_NORMAL:= TRUNC(V_SUELDO/100000);
    
        VALOR_MOVIL_NORMAL:=   ROUND((V_SUELDO*PORC_MOVIL_NORMAL)/100);
    
    
        IF V_COMUNA = :B_COMUNA1     THEN
            VALOR_MOVIL_EXTRA:= 20000;
        ELSIF V_COMUNA = :B_COMUNA2        THEN
            VALOR_MOVIL_EXTRA:= 25000;
        ELSIF V_COMUNA = :B_COMUNA3        THEN
            VALOR_MOVIL_EXTRA:= 30000;
        ELSIF V_COMUNA = :B_COMUNA4        THEN
            VALOR_MOVIL_EXTRA:= 35000;
        ELSIF V_COMUNA = :B_COMUNA5        THEN
            VALOR_MOVIL_EXTRA:= 40000;
        ELSE 
            VALOR_MOVIL_EXTRA:= 0;
        END IF;
    
        VALOR_TOTAL_MOVIL:= VALOR_MOVIL_NORMAL+VALOR_MOVIL_EXTRA;
        
        INSERT INTO PROY_MOVILIZACION VALUES(:B_ANNO_PROCESO, V_ID, V_RUN, V_DV, V_NOMBRE, V_COMUNA, V_SUELDO, PORC_MOVIL_NORMAL, VALOR_MOVIL_NORMAL, VALOR_MOVIL_EXTRA, VALOR_TOTAL_MOVIL);
        
        V_MIN := V_MIN + 10;
        EXIT WHEN V_MIN > V_MAX;
    END LOOP;
END;
SELECT * FROM PROY_MOVILIZACION;