--CASO 1--
VARIABLE B_RUN NUMBER;
EXEC :B_RUN:=&RUT;

DECLARE
    V_CLIENTE       NUMBER;
    V_RUT           NUMBER;
    V_DV            VARCHAR2(100);
    V_NOMBRE        VARCHAR2(100);
    V_OFICIO        VARCHAR2(100);
    V_NACIMIENTO    DATE;
    V_MONTO         NUMBER;
    FECHA_CUM       VARCHAR2(100);
    OBSERVACION     VARCHAR2(100) := '';
    GIFT_CARD       NUMBER;
    RUT_COMPLETO     VARCHAR2(100);

BEGIN
    SELECT C.NRO_CLIENTE, 
    C.NUMRUN, 
    C.DVRUN,
    C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO,
    PO.NOMBRE_PROF_OFIC,
    C.FECHA_NACIMIENTO,
    SUM(IC.MONTO_TOTAL_AHORRADO)
    INTO V_CLIENTE, V_RUT, V_DV, V_NOMBRE, V_OFICIO, V_NACIMIENTO, V_MONTO
    FROM CLIENTE C
    JOIN PROFESION_OFICIO PO ON (C.COD_PROF_OFIC = PO.COD_PROF_OFIC)
    JOIN PRODUCTO_INVERSION_CLIENTE IC ON (C.NRO_CLIENTE = IC.NRO_CLIENTE)
    WHERE C.NUMRUN = '12362093'
    GROUP BY C.NRO_CLIENTE, C.NUMRUN, C.DVRUN, C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO,
    PO.NOMBRE_PROF_OFIC, C.FECHA_NACIMIENTO;
    
    RUT_COMPLETO:= TO_CHAR(V_RUT,'99G999G999')||'-'||V_DV;

    FECHA_CUM := TO_CHAR(V_NACIMIENTO, 'DD "de" Month');
   
    IF EXTRACT(MONTH FROM V_NACIMIENTO) = EXTRACT(MONTH FROM SYSDATE)-1      THEN
        OBSERVACION := NULL;
        IF V_MONTO BETWEEN 0 AND 900000             THEN
            GIFT_CARD:= 0;
        ELSIF V_MONTO BETWEEN 900001 AND 2000000    THEN
            GIFT_CARD:= 50000;
        ELSIF V_MONTO BETWEEN 2000001 AND 5000000   THEN
            GIFT_CARD:= 100000;
        ELSIF V_MONTO BETWEEN 5000001 AND 8000000   THEN
            GIFT_CARD:= 200000;
        ELSIF V_MONTO BETWEEN 8000001 AND 15000000   THEN
            GIFT_CARD:= 300000;
        ELSE
            GIFT_CARD:= NULL;
        END IF;
    ELSE
        OBSERVACION := 'El cliente no está de cumpleaños en el mes procesado';
        GIFT_CARD:= 'NULO';
    END IF;
    
    

    
    INSERT INTO CUMPLEANNO_CLIENTE VALUES(V_CLIENTE, RUT_COMPLETO, V_NOMBRE, V_OFICIO, FECHA_CUM, GIFT_CARD, OBSERVACION);
END;
SELECT * FROM CUMPLEANNO_CLIENTE