--CASO 4--
SET SERVEROUTPUT ON;

DECLARE

V_CSIN_AMOBLAR      VARCHAR2(200):= 'Casa sin Amoblar';
V_C_AMOBLADA        VARCHAR2(200):= 'Casa Amoblada';
V_DPTOAIN_AMOBLAR   VARCHAR2(200):= 'Departamento sin Amoblar';
V_DPTO_AMOBLADO     VARCHAR2(200):= 'Departamento Amoblado';
V_LOCAL_COMERCIAL   VARCHAR2(200):= 'Local Comercial';
V_PARCELA_SIN_CASA  VARCHAR2(200):= 'Parcela sin Casa';
V_PARCELA_CON_CASA  VARCHAR2(200):= 'Parcela con Casa';
V_SITIO             VARCHAR(200):= 'Sitio';

V_CANT      NUMBER;
V_DESC      VARCHAR2(200);
V_VALOR     NUMBER;


BEGIN
    SELECT TP.DESC_TIPO_PROPIEDAD,
    COUNT(P.ID_TIPO_PROPIEDAD),
    SUM(P.VALOR_ARRIENDO)
    INTO V_DESC, V_CANT, V_VALOR
    FROM PROPIEDAD P
    JOIN TIPO_PROPIEDAD TP ON (P.ID_TIPO_PROPIEDAD=TP.ID_TIPO_PROPIEDAD)
    WHERE TP.DESC_TIPO_PROPIEDAD = V_CSIN_AMOBLAR
    GROUP BY TP.DESC_TIPO_PROPIEDAD;
    
    DBMS_OUTPUT.PUT_LINE('RESUMEN DE: '||V_CSIN_AMOBLAR);
    DBMS_OUTPUT.PUT_LINE('Total de Propiedades: '||V_CANT);
    DBMS_OUTPUT.PUT_LINE('Valor Total Arriendo: '||TO_CHAR(V_VALOR, '$9G999G999'));
    
    SELECT TP.DESC_TIPO_PROPIEDAD,
    COUNT(P.ID_TIPO_PROPIEDAD),
    SUM(P.VALOR_ARRIENDO)
    INTO V_DESC, V_CANT, V_VALOR
    FROM PROPIEDAD P
    JOIN TIPO_PROPIEDAD TP ON (P.ID_TIPO_PROPIEDAD=TP.ID_TIPO_PROPIEDAD)
    WHERE TP.DESC_TIPO_PROPIEDAD = V_C_AMOBLADA
    GROUP BY TP.DESC_TIPO_PROPIEDAD;
    
    DBMS_OUTPUT.PUT_LINE('RESUMEN DE: '||V_C_AMOBLADA);
    DBMS_OUTPUT.PUT_LINE('Total de Propiedades: '||V_CANT);
    DBMS_OUTPUT.PUT_LINE('Valor Total Arriendo: '||TO_CHAR(V_VALOR, '$9G999G999'));
    
    SELECT TP.DESC_TIPO_PROPIEDAD,
    COUNT(P.ID_TIPO_PROPIEDAD),
    SUM(P.VALOR_ARRIENDO)
    INTO V_DESC, V_CANT, V_VALOR
    FROM PROPIEDAD P
    JOIN TIPO_PROPIEDAD TP ON (P.ID_TIPO_PROPIEDAD=TP.ID_TIPO_PROPIEDAD)
    WHERE TP.DESC_TIPO_PROPIEDAD = V_DPTOAIN_AMOBLAR
    GROUP BY TP.DESC_TIPO_PROPIEDAD;
    
    DBMS_OUTPUT.PUT_LINE('RESUMEN DE: '||V_DPTOAIN_AMOBLAR);
    DBMS_OUTPUT.PUT_LINE('Total de Propiedades: '||V_CANT);
    DBMS_OUTPUT.PUT_LINE('Valor Total Arriendo: '||TO_CHAR(V_VALOR, '$9G999G999'));
    
    SELECT TP.DESC_TIPO_PROPIEDAD,
    COUNT(P.ID_TIPO_PROPIEDAD),
    SUM(P.VALOR_ARRIENDO)
    INTO V_DESC, V_CANT, V_VALOR
    FROM PROPIEDAD P
    JOIN TIPO_PROPIEDAD TP ON (P.ID_TIPO_PROPIEDAD=TP.ID_TIPO_PROPIEDAD)
    WHERE TP.DESC_TIPO_PROPIEDAD = V_DPTO_AMOBLADO
    GROUP BY TP.DESC_TIPO_PROPIEDAD;
    
    DBMS_OUTPUT.PUT_LINE('RESUMEN DE: '||V_DPTO_AMOBLADO);
    DBMS_OUTPUT.PUT_LINE('Total de Propiedades: '||V_CANT);
    DBMS_OUTPUT.PUT_LINE('Valor Total Arriendo: '||TO_CHAR(V_VALOR, '$9G999G999'));
    
    SELECT TP.DESC_TIPO_PROPIEDAD,
    COUNT(P.ID_TIPO_PROPIEDAD),
    SUM(P.VALOR_ARRIENDO)
    INTO V_DESC, V_CANT, V_VALOR
    FROM PROPIEDAD P
    JOIN TIPO_PROPIEDAD TP ON (P.ID_TIPO_PROPIEDAD=TP.ID_TIPO_PROPIEDAD)
    WHERE TP.DESC_TIPO_PROPIEDAD = V_LOCAL_COMERCIAL
    GROUP BY TP.DESC_TIPO_PROPIEDAD;
    
    DBMS_OUTPUT.PUT_LINE('RESUMEN DE: '||V_LOCAL_COMERCIAL);
    DBMS_OUTPUT.PUT_LINE('Total de Propiedades: '||V_CANT);
    DBMS_OUTPUT.PUT_LINE('Valor Total Arriendo: '||TO_CHAR(V_VALOR, '$9G999G999'));
    
    SELECT TP.DESC_TIPO_PROPIEDAD,
    COUNT(P.ID_TIPO_PROPIEDAD),
    SUM(P.VALOR_ARRIENDO)
    INTO V_DESC, V_CANT, V_VALOR
    FROM PROPIEDAD P
    JOIN TIPO_PROPIEDAD TP ON (P.ID_TIPO_PROPIEDAD=TP.ID_TIPO_PROPIEDAD)
    WHERE TP.DESC_TIPO_PROPIEDAD = V_PARCELA_SIN_CASA
    GROUP BY TP.DESC_TIPO_PROPIEDAD;
    
    DBMS_OUTPUT.PUT_LINE('RESUMEN DE: '||V_PARCELA_SIN_CASA);
    DBMS_OUTPUT.PUT_LINE('Total de Propiedades: '||V_CANT);
    DBMS_OUTPUT.PUT_LINE('Valor Total Arriendo: '||TO_CHAR(V_VALOR, '$9G999G999'));
    
    SELECT TP.DESC_TIPO_PROPIEDAD,
    COUNT(P.ID_TIPO_PROPIEDAD),
    SUM(P.VALOR_ARRIENDO)
    INTO V_DESC, V_CANT, V_VALOR
    FROM PROPIEDAD P
    JOIN TIPO_PROPIEDAD TP ON (P.ID_TIPO_PROPIEDAD=TP.ID_TIPO_PROPIEDAD)
    WHERE TP.DESC_TIPO_PROPIEDAD = V_PARCELA_CON_CASA
    GROUP BY TP.DESC_TIPO_PROPIEDAD;
    
    DBMS_OUTPUT.PUT_LINE('RESUMEN DE: '||V_PARCELA_CON_CASA);
    DBMS_OUTPUT.PUT_LINE('Total de Propiedades: '||V_CANT);
    DBMS_OUTPUT.PUT_LINE('Valor Total Arriendo: '||TO_CHAR(V_VALOR, '$9G999G999'));
    
    SELECT TP.DESC_TIPO_PROPIEDAD,
    COUNT(P.ID_TIPO_PROPIEDAD),
    SUM(P.VALOR_ARRIENDO)
    INTO V_DESC, V_CANT, V_VALOR
    FROM PROPIEDAD P
    JOIN TIPO_PROPIEDAD TP ON (P.ID_TIPO_PROPIEDAD=TP.ID_TIPO_PROPIEDAD)
    WHERE TP.DESC_TIPO_PROPIEDAD = V_SITIO
    GROUP BY TP.DESC_TIPO_PROPIEDAD;
    
    DBMS_OUTPUT.PUT_LINE('RESUMEN DE: '||V_SITIO);
    DBMS_OUTPUT.PUT_LINE('Total de Propiedades: '||V_CANT);
    DBMS_OUTPUT.PUT_LINE('Valor Total Arriendo: '||TO_CHAR(V_VALOR, '$9G999G999'));
    

END;