--CASO 2--
SET SERVEROUTPUT ON

VAR B_RUN VARCHAR2(20)
EXEC :B_RUN:=&RUN

VAR B_RENTA_MINIMA VARCHAR2(20)
EXEC :B_RENTA_MINIMA:=&RENTA

DECLARE
V_NOMBRE    VARCHAR2(100);
V_RUT       VARCHAR2(100);
V_CIVIL     VARCHAR2(20);
V_RENTA     NUMBER;


BEGIN
    SELECT c.NOMBRE_CLI||' '||c.APPATERNO_CLI||' '||c.APMATERNO_CLI,
    c.NUMRUT_CLI||'-'||c.DVRUT_CLI,
    e.DESC_ESTCIVIL,
    c.RENTA_CLI
    INTO V_NOMBRE, V_RUT, V_CIVIL, V_RENTA
    FROM CLIENTE c JOIN ESTADO_CIVIL e ON (c.ID_ESTCIVIL = e.ID_ESTCIVIL)
    WHERE c.NUMRUT_CLI =:B_RUN AND c.RENTA_CLI >= :B_RENTA_MINIMA;
    
    DBMS_OUTPUT.PUT_LINE('DATOS DEL CLIENTE');
    dbms_output.PUT_LINE('-----------------');
    dbms_output.PUT_LINE('NOMBRE: '||V_NOMBRE);
    dbms_output.PUT_LINE('RUN: '||V_RUT);
    dbms_output.PUT_LINE('ESTADO CIVIL: '||V_CIVIL);
    dbms_output.PUT_LINE('RENTA: '||TO_CHAR(V_RENTA, '$999G999G999'));
    


--FERNANDO CADIZ 12861354
END;

