--CASO 1--
SET SERVEROUTPUT ON;
VAR B_PORCENTAJE NUMBER
EXEC :B_PORCENTAJE:=&PORCENTAJE

VAR B_RUN VARCHAR2(20)
EXEC :B_RUN:=&RUN
 
DECLARE
    V_NOMBRE    VARCHAR2(20);
    V_RUT       VARCHAR2(20);
    V_SUELDO    NUMBER(20);
    V_BONIF NUMBER(20);

BEGIN
    SELECT NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP, 
    NUMRUT_EMP||'-'||DVRUT_EMP,
    SUELDO_EMP
    INTO V_NOMBRE, V_RUT, V_SUELDO
    FROM EMPLEADO
    WHERE NUMRUT_EMP =:B_RUN;
    
    V_BONIF := (V_SUELDO *:B_PORCENTAJE)/100;
    
    DBMS_OUTPUT.PUT_LINE('DATOS CALCULO BONIFICACION EXTRA DEL '||:B_PORCENTAJE||'% DEL SUELDO');
    DBMS_OUTPUT.PUT_LINE('Nombre Empleado: '||V_NOMBRE);
    DBMS_OUTPUT.PUT_LINE('RUN: '||V_RUT);
    DBMS_OUTPUT.PUT_LINE('Sueldo: '||V_SUELDO);
    DBMS_OUTPUT.PUT_LINE('Bonificación extra: '||V_BONIF);
    
    --MARCO  11846972
    --MARIA 18560875
    
END;

