--CASO 4--
VARIABLE B_PATENTE VARCHAR2(100);
EXEC :B_PATENTE:=&PATENTE; --ERROR AL COLOCAR LA BIND PARA LA SENTENCIA WHERE CUANDO SE COLOCA TIRA ERROR DE NO DATA FOUND DEBE
                            --DEBER SER POR DIFERENCIA DE TIPO DE DATO

DECLARE
V_PATENTE               VARCHAR2(100);
V_INI                   DATE;
V_DIAS                  NUMBER;
V_DEVO                  DATE;
ANNO_PROCESO            NUMBER:=EXTRACT(MONTH FROM SYSDATE);
MES_ANNO        VARCHAR2(100):= TO_CHAR(SYSDATE, 'MMYYYY');
DIAS_RECORRIDOS         NUMBER;
DIAS_PASADOS            NUMBER;
VALOR_MULTA             NUMBER:=25500;
VALOR_MULTA_TOTAL       NUMBER;

BEGIN
    SELECT NRO_PATENTE, FECHA_INI_ARRIENDO, DIAS_SOLICITADOS, FECHA_DEVOLUCION
    INTO V_PATENTE, V_INI, V_DIAS, V_DEVO
    FROM ARRIENDO_CAMION
    WHERE EXTRACT(MONTH FROM FECHA_DEVOLUCION) = EXTRACT(MONTH FROM SYSDATE)-3 AND NRO_PATENTE = 'AA1001'
    AND FECHA_DEVOLUCION - DIAS_SOLICITADOS > FECHA_INI_ARRIENDO;
    
    DIAS_RECORRIDOS:= EXTRACT(DAY FROM V_DEVO) - EXTRACT(DAY FROM V_INI);
    
    DIAS_PASADOS:= DIAS_RECORRIDOS-V_DIAS;
    VALOR_MULTA_TOTAL:=DIAS_PASADOS*VALOR_MULTA;
    INSERT INTO MULTA_ARRIENDO VALUES(MES_ANNO, V_PATENTE, V_INI, V_DIAS, V_DEVO, DIAS_PASADOS, VALOR_MULTA_TOTAL);

        


END;

SELECT * FROM MULTA_ARRIENDO;