--CASO 1--

VARIABLE B_RUN NUMBER;
EXEC :B_RUN:=&RUT;

DECLARE
    V_NUMRUN    VARCHAR2(100);
    V_DV        VARCHAR2(100);
    V_NOMBRE    VARCHAR2(100);
    V_SUELDO    NUMBER;
    V_COMUNA    NUMBER;
    ANNO_PROCESO        NUMBER:=EXTRACT(YEAR FROM SYSDATE);
    PORC_MOVIL_NORMAL   NUMBER;
    VALOR_MOVIL_NORMAL  NUMBER;
    VALOR_MOVIL_ADICIONAL   NUMBER;
    VALOR_TOTAL_MOVIL   NUMBER;

BEGIN
    SELECT NUMRUN_EMP,
    DVRUN_EMP,
    PNOMBRE_EMP||' '||SNOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP,
    SUELDO_BASE,
    ID_COMUNA
    INTO V_NUMRUN, V_DV, V_NOMBRE, V_SUELDO, V_COMUNA
    FROM EMPLEADO
    WHERE NUMRUN_EMP=:B_RUN;
    
    PORC_MOVIL_NORMAL:=TRUNC(V_SUELDO/100000);
    VALOR_MOVIL_NORMAL:=TRUNC((V_SUELDO*PORC_MOVIL_NORMAL)/100);
    
    IF V_COMUNA = 117   THEN
        VALOR_MOVIL_ADICIONAL:= 20000;
    ELSIF V_COMUNA = 118    THEN
        VALOR_MOVIL_ADICIONAL:= 25000;
    ELSIF V_COMUNA = 119    THEN
        VALOR_MOVIL_ADICIONAL:= 30000;
    ELSIF V_COMUNA = 120    THEN
        VALOR_MOVIL_ADICIONAL:= 35000;
    ELSIF V_COMUNA = 121    THEN
        VALOR_MOVIL_ADICIONAL:= 40000;
    ELSE
        VALOR_MOVIL_ADICIONAL:= 0;
    END IF;
    
    VALOR_TOTAL_MOVIL:= VALOR_MOVIL_NORMAL+VALOR_MOVIL_ADICIONAL;
    
    INSERT INTO PROY_MOVILIZACION VALUES(ANNO_PROCESO, V_NUMRUN, V_DV, V_NOMBRE, V_SUELDO, PORC_MOVIL_NORMAL, VALOR_MOVIL_NORMAL, VALOR_MOVIL_ADICIONAL, VALOR_TOTAL_MOVIL); 
    
END;

SELECT * FROM PROY_MOVILIZACION;
--RUT A PROBAR 11846972, 12272880, 12113369, 11999100, 12868553