--CASO 2--

VARIABLE B_RUN NUMBER;
EXEC :B_RUN:=&RUT;

DECLARE
    V_NUMRUN        NUMBER;
    V_DV            NUMBER;
    V_PNOMBRE       VARCHAR2(100);
    V_SNOMBRE       VARCHAR2(100);
    V_APPATERNO     VARCHAR2(100);
    V_APMATERNO     VARCHAR2(100);
    V_SUELDO        NUMBER;
    V_FCONTRATO     DATE;
    V_FNAC          DATE;
    V_EST_CIVIL     NUMBER;
    V_COMUNA        VARCHAR2(100);
    MES_ANNO        VARCHAR2(100):= TO_CHAR(SYSDATE, 'MMYYYY');
    NOMBRE_EMPLEADO VARCHAR2(100);
    NOMBRE_USUARIO  VARCHAR2(100):='';
    ANNOS_TRABAJADOS NUMBER;
    CLAVE_USUARIO   VARCHAR2(100);
    
BEGIN
    SELECT E.NUMRUN_EMP,
    E.DVRUN_EMP,
    E.PNOMBRE_EMP,
    E.SNOMBRE_EMP,
    E.APPATERNO_EMP,
    E.APMATERNO_EMP,
    E.SUELDO_BASE,
    E.FECHA_CONTRATO,
    E.FECHA_NAC,
    E.ID_ESTADO_CIVIL,
    C.NOMBRE_COMUNA
    INTO V_NUMRUN, V_DV, V_PNOMBRE, V_SNOMBRE, V_APPATERNO, V_APMATERNO, V_SUELDO, 
    V_FCONTRATO, V_FNAC, V_EST_CIVIL, V_COMUNA
    FROM EMPLEADO E
    JOIN COMUNA C ON (E.ID_COMUNA=C.ID_COMUNA)
    WHERE NUMRUN_EMP = :B_RUN;
    
    NOMBRE_EMPLEADO:= V_PNOMBRE||' '||V_SNOMBRE||' '||V_APPATERNO||' '||V_APMATERNO;
    
    NOMBRE_USUARIO:= SUBSTR(V_PNOMBRE,1,3);
    NOMBRE_USUARIO:= NOMBRE_USUARIO||LENGTH(V_PNOMBRE);
    NOMBRE_USUARIO:= NOMBRE_USUARIO||'*';
    NOMBRE_USUARIO:= NOMBRE_USUARIO||SUBSTR(V_SUELDO,-1,1);
    NOMBRE_USUARIO:= NOMBRE_USUARIO||V_DV;
    
    ANNOS_TRABAJADOS:= ROUND(MONTHS_BETWEEN(SYSDATE, V_FCONTRATO) / 12);
    IF ANNOS_TRABAJADOS < 10 THEN
        NOMBRE_USUARIO:= NOMBRE_USUARIO||ANNOS_TRABAJADOS;
        NOMBRE_USUARIO:= NOMBRE_USUARIO||'X';
    ELSE
        NOMBRE_USUARIO:= NOMBRE_USUARIO||ANNOS_TRABAJADOS;
    END IF;
    
    CLAVE_USUARIO:=SUBSTR(V_NUMRUN,3,1);
    CLAVE_USUARIO:=CLAVE_USUARIO||EXTRACT(YEAR FROM V_FNAC)+2;
    CLAVE_USUARIO:=CLAVE_USUARIO||SUBSTR((V_SUELDO-1),-3,3);
    IF V_EST_CIVIL = 10 OR V_EST_CIVIL = 60     THEN
        CLAVE_USUARIO:=CLAVE_USUARIO||SUBSTR(LOWER(V_APPATERNO),1,2);
    ELSIF V_EST_CIVIL = 20 OR V_EST_CIVIL = 30  THEN
        CLAVE_USUARIO:=CLAVE_USUARIO||(SUBSTR(LOWER(V_APPATERNO),1,1)||SUBSTR(LOWER(V_APPATERNO),-1,1));
    ELSIF V_EST_CIVIL = 40                      THEN
        CLAVE_USUARIO:=CLAVE_USUARIO||SUBSTR(LOWER(V_APPATERNO),-2,2);
    ELSIF V_EST_CIVIL= 50                       THEN
       CLAVE_USUARIO:= CLAVE_USUARIO||SUBSTR(LOWER(V_APPATERNO),-1,2);
    END IF;
    
    CLAVE_USUARIO:=CLAVE_USUARIO||MES_ANNO;
    CLAVE_USUARIO:=CLAVE_USUARIO||SUBSTR(V_COMUNA,1,1);
    
    
    INSERT INTO USUARIO_CLAVE VALUES(MES_ANNO, V_NUMRUN, V_DV,NOMBRE_EMPLEADO, NOMBRE_USUARIO,CLAVE_USUARIO );
END;
SELECT * FROM USUARIO_CLAVE;
TRUNCATE TABLE USUARIO_CLAVE;