--CASO 3--
VARIABLE B_PATENTE VARCHAR2(100);
EXEC :B_PATENTE:=&PATENTE; --ERROR AL COLOCAR LA BIND PARA LA SENTENCIA WHERE CUANDO SE COLOCA TIRA ERROR DE NO DATA FOUND DEBE
                            --DEBER SER POR DIFERENCIA DE TIPO DE DATO

DECLARE
V_PATENTE               VARCHAR2(100);
V_ARR_DIA               NUMBER;
V_GARANTIA_DIA          NUMBER;
V_VECES                 NUMBER;
ANNO_PROCESO            NUMBER:=EXTRACT(YEAR FROM SYSDATE);

BEGIN
    SELECT C.NRO_PATENTE,
    C.VALOR_ARRIENDO_DIA,
    C.VALOR_GARANTIA_DIA,
    COUNT(AC.NRO_PATENTE)
    INTO V_PATENTE, V_ARR_DIA, V_GARANTIA_DIA, V_VECES
    FROM CAMION C
    JOIN ARRIENDO_CAMION AC ON(C.NRO_PATENTE=AC.NRO_PATENTE)
    WHERE C.NRO_PATENTE = 'BT1002' 
    AND EXTRACT(YEAR FROM AC.FECHA_INI_ARRIENDO) = EXTRACT(YEAR FROM SYSDATE)-1 
    GROUP BY C.NRO_PATENTE, C.VALOR_ARRIENDO_DIA, C.VALOR_GARANTIA_DIA;
    
    INSERT INTO HIST_ARRIENDO_ANUAL_CAMION VALUES(ANNO_PROCESO, V_PATENTE, V_ARR_DIA, V_GARANTIA_DIA, V_VECES);
    
    SAVEPOINT V1;
    IF V_VECES < 5          THEN
        UPDATE CAMION
        SET VALOR_ARRIENDO_DIA = ROUND(VALOR_ARRIENDO_DIA * 0.775),
        VALOR_GARANTIA_DIA = ROUND(VALOR_GARANTIA_DIA * 0.775)
        WHERE NRO_PATENTE = V_PATENTE;
    END IF;
    COMMIT;
        

END;


SELECT * FROM HIST_ARRIENDO_ANUAL_CAMION;
SELECT * FROM CAMION;
TRUNCATE TABLE HIST_ARRIENDO_ANUAL_CAMION;